### ISSUE TITLE
error in latest master with npm start

### ISSUE THREAD

**Issue by coleGillespie** [bigboringsystem/bigboringsystem#176]
currently not able to test locally
```
[cole@localhost bigboringsystem]$ npm start

> bigboringsystem@1.0.0 start /home/cole/Public/github/bigboringsystem
> npm run watch-styles & nodemon index.js

exception in nodemon killing node
Error: watch ENOSPC
    at errnoException (fs.js:1030:11)
    at FSWatcher.start (fs.js:1062:11)
    at Object.fs.watch (fs.js:1087:11)
    at Function.check (/home/cole/Public/github/bigboringsystem/node_modules/nodemon/lib/config/watchable.js:39:6)
    at alternativeCheck (/home/cole/Public/github/bigboringsystem/node_modules/nodemon/lib/config/checkWatchSupport.js:33:15)
    at checkWatchSupport (/home/cole/Public/github/bigboringsystem/node_modules/nodemon/lib/config/checkWatchSupport.js:62:5)
    at /home/cole/Public/github/bigboringsystem/node_modules/nodemon/lib/config/index.js:74:5
    at normaliseRules (/home/cole/Public/github/bigboringsystem/node_modules/nodemon/lib/config/load.js:119:3)
    at ready (/home/cole/Public/github/bigboringsystem/node_modules/nodemon/lib/config/load.js:60:9)
    at /home/cole/Public/github/bigboringsystem/node_modules/nodemon/lib/config/load.js:72:13

----------------------------------------------------------
If appropriate, please file an error with the output from:
$ node /home/cole/Public/github/bigboringsystem/node_modules/.bin/nodemon index.js --dump
At http://github.com/remy/nodemon/issues/new
----------------------------------------------------------

9 Jan 20:10:10 - [nodemon] v1.2.1
9 Jan 20:10:10 - [nodemon] to restart at any time, enter `rs`
9 Jan 20:10:10 - [nodemon] watching: *.*
9 Jan 20:10:10 - [nodemon] starting `node index.js`
npm ERR! weird error 1
npm ERR! not ok code 0
[cole@localhost bigboringsystem]$ 
> bigboringsystem@1.0.0 watch-styles /home/cole/Public/github/bigboringsystem
> stylus -c -w -m public/styl/main.styl -o public/css/bundle.min.css

  watching /home/cole/Public/github/bigboringsystem/node_modules/stylus/lib/functions/index.styl
  watching public/styl/reset.styl
  watching public/styl/global.styl
  compiled public/css/bundle.min.css
  watching public/styl/main.styl
  generated public/css/bundle.min.css.map
```

**Comment by ednapiranha** [comment]
try again?

**Comment by TheAlphaNerd** [comment]
try this 

```killall node && rm -rf node_modules && npm i```

This will kill any rogue process, and give you a fresh install of node modules.  Should fix the problem

**Comment by isaacs** [comment]
@coleGillespie Is this a Linux box?  If so, try this: http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

The system has a max number of file descriptors that it'll open to watch things.  This bumps the limit up.

**Comment by coleGillespie** [comment]
was fedora 21 @isaacs

**Comment by isaacs** [comment]
@coleGillespie Awesome, then yes, the SO post I linked to is your answer.
